#!/usr/bin/env node
/**
 * Flags, bundled at build time.
 *
 *   npm run build:flags
 *
 * Writes two things:
 *
 *   src/flag-codes.js   the lookup table, as an explicit and reviewable file:
 *                       ISO 3166-1 numeric (what the world topology carries)
 *                       and alpha-3 (what the boundary registry carries) to
 *                       alpha-2 (what flag-icons names its files by)
 *   public/flags/…      only the SVGs that table can reach, in the 4:3 set for
 *                       fills and the 1:1 set for the micro-state disc
 *
 * The rule the whole table follows: a unit gets a flag only when its OWN code
 * resolves to one. No matching by name, no fallback flag, and no flag for a
 * code the boundary data does not assign. Kosovo is the example worth naming —
 * flag-icons ships an `xk` flag, Natural Earth assigns Kosovo no ISO code, so
 * Kosovo gets no flag. The tool does not take a position on sovereignty; it
 * reports what the boundary data says and nothing else.
 *
 * flag-icons also carries non-ISO sets — `eu`, `un`, `gb-sct`, `es-ct`, `arab`
 * and so on. None of them are reachable from an ISO code, so none are copied.
 *
 * Nothing is fetched at runtime. The tool must work offline, and a published
 * page cannot load remote images into a canvas it then exports.
 */

import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';

import { ROOT, readRegistry } from './lib/registry.js';

const require = createRequire(import.meta.url);
const countries = require('i18n-iso-countries');

const FLAGS_SRC = path.join(ROOT, 'node_modules', 'flag-icons', 'flags');
const FLAGS_OUT = path.join(ROOT, 'public', 'flags');
const TABLE_OUT = path.join(ROOT, 'src', 'flag-codes.js');
const WORLD = path.join(ROOT, 'public', 'data', 'world-50m.topo.json');

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'flag-icons', 'package.json'), 'utf8'));

const hasFlag = (a2) => fs.existsSync(path.join(FLAGS_SRC, '4x3', `${a2}.svg`)) &&
                        fs.existsSync(path.join(FLAGS_SRC, '1x1', `${a2}.svg`));

async function main() {
  const world = JSON.parse(await fsp.readFile(WORLD, 'utf8'));
  const geoms = world.objects.countries.geometries;

  const numeric = {};           // '036' -> 'au'
  const unresolved = [];        // { unit, code, why }

  for (const g of geoms) {
    const unit = g.properties && g.properties.name;
    if (!unit) continue;
    const code = g.id == null ? null : String(g.id).padStart(3, '0');
    if (!code) { unresolved.push({ unit, code: null, why: 'the boundary data assigns no ISO code' }); continue; }

    const a2 = countries.numericToAlpha2(code);
    if (!a2) { unresolved.push({ unit, code, why: 'not an ISO 3166-1 numeric code' }); continue; }
    const lower = a2.toLowerCase();
    if (!hasFlag(lower)) { unresolved.push({ unit, code, why: `flag-icons ${pkg.version} has no ${lower}` }); continue; }
    numeric[code] = lower;
  }

  // The registry keys countries by alpha-3. Only these reach the layer picker
  // and the export badge, so only these are listed.
  const registry = readRegistry();
  const alpha3 = {};
  for (const iso of new Set(Object.values(registry.sources).map((e) => e.iso))) {
    const a2 = countries.alpha3ToAlpha2(iso);
    if (a2 && hasFlag(a2.toLowerCase())) alpha3[iso] = a2.toLowerCase();
    else unresolved.push({ unit: `registry ${iso}`, code: iso, why: 'no alpha-2 or no flag' });
  }

  const needed = [...new Set([...Object.values(numeric), ...Object.values(alpha3)])].sort();

  await fsp.rm(FLAGS_OUT, { recursive: true, force: true });
  for (const set of ['4x3', '1x1']) {
    await fsp.mkdir(path.join(FLAGS_OUT, set), { recursive: true });
    for (const a2 of needed) {
      await fsp.copyFile(path.join(FLAGS_SRC, set, `${a2}.svg`), path.join(FLAGS_OUT, set, `${a2}.svg`));
    }
  }
  await fsp.copyFile(path.join(ROOT, 'node_modules', 'flag-icons', 'LICENSE'), path.join(FLAGS_OUT, 'LICENSE'));

  const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
  const body = `/**
 * Generated by scripts/build-flags.js from i18n-iso-countries and flag-icons
 * ${pkg.version} (MIT). Committed so every mapping can be read and reviewed.
 *
 * A unit gets a flag only when its own code appears here. Anything not listed
 * — including every unit in UNRESOLVED — stays in the unassigned land tone.
 */

/** ISO 3166-1 numeric, as the world topology carries it, to alpha-2. */
export const NUMERIC_TO_A2 = ${JSON.stringify(sorted(numeric), null, 2)};

/** ISO 3166-1 alpha-3, as the boundary registry carries it, to alpha-2. */
export const ALPHA3_TO_A2 = ${JSON.stringify(sorted(alpha3), null, 2)};

/** Units deliberately left without a flag, and why. */
export const UNRESOLVED = ${JSON.stringify(unresolved, null, 2)};

export const FLAG_SET = { name: 'flag-icons', version: '${pkg.version}', licence: 'MIT' };
`;
  await fsp.writeFile(TABLE_OUT, body);

  let bytes = 0;
  for (const set of ['4x3', '1x1']) {
    for (const f of await fsp.readdir(path.join(FLAGS_OUT, set))) {
      bytes += (await fsp.stat(path.join(FLAGS_OUT, set, f))).size;
    }
  }
  console.log(`${Object.keys(numeric).length} world units resolve to a flag`);
  console.log(`${Object.keys(alpha3).length} registry countries resolve to a flag`);
  console.log(`${needed.length} flags copied, ${(bytes / 1024).toFixed(0)} KB across both sets`);
  console.log(`${unresolved.length} left without a flag:`);
  for (const u of unresolved) console.log(`  ${u.unit}${u.code ? ` (${u.code})` : ''} — ${u.why}`);
}

main().catch((err) => { console.error('build failed:', err.message); process.exit(1); });
